#!/bin/bash
# Podman Exercises - Commands to practice

echo "=== Podman Basic Commands ==="
echo ""
echo "1. Check Podman version:"
echo "   podman --version"
echo ""
echo "2. Pull a simple image:"
echo "   podman pull hello-world"
echo ""
echo "3. List downloaded images:"
echo "   podman images"
echo ""
echo "4. Run the hello-world container:"
echo "   podman run hello-world"
echo ""
echo "5. List running containers:"
echo "   podman ps"
echo ""
echo "6. List all containers (including stopped):"
echo "   podman ps -a"
echo ""
echo "7. Pull and run an interactive Alpine Linux container:"
echo "   podman run -it alpine sh"
echo "   (Type 'exit' to leave the container)"
echo ""
echo "8. Run a container in the background:"
echo "   podman run -d --name my-nginx -p 8080:80 nginx"
echo ""
echo "9. Check running containers:"
echo "    podman ps"
echo ""
echo "10. Stop a container:"
echo "    podman stop my-nginx"
echo ""
echo "11. Remove a container:"
echo "    podman rm my-nginx"
echo ""
echo "12. Remove an image:"
echo "    podman rmi nginx"
echo ""

