#!/bin/bash
# User and Permissions Exercises

echo "=== User and Permissions Exercises ==="
echo ""
echo "Exercise 1: Who am I?"
echo "  whoami                 # Current username"
echo "  id                     # User ID and group IDs"
echo "  groups                 # Groups you belong to"
echo ""
echo "Exercise 2: Understanding file permissions"
echo "  ls -l file.txt         # View file permissions"
echo ""
echo "  Permission format: -rwxrwxrwx"
echo "  - First character: file type (- = file, d = directory)"
echo "  - Next 3: owner permissions (read, write, execute)"
echo "  - Next 3: group permissions"
echo "  - Last 3: others permissions"
echo ""
echo "Exercise 3: Changing file permissions"
echo "  chmod +x script.sh     # Add execute permission for everyone"
echo "  chmod -x script.sh     # Remove execute permission"
echo "  chmod u+x script.sh    # Add execute for user (owner)"
echo "  chmod g+w script.sh    # Add write for group"
echo "  chmod o-r script.sh    # Remove read for others"
echo ""
echo "  Using numeric notation:"
echo "  chmod 755 script.sh    # rwxr-xr-x"
echo "  chmod 644 file.txt     # rw-r--r--"
echo "  chmod 700 private.sh   # rwx------"
echo ""
echo "  Numeric values:"
echo "  4 = read (r)"
echo "  2 = write (w)"
echo "  1 = execute (x)"
echo "  Add them: 7=rwx, 6=rw-, 5=r-x, 4=r--"
echo ""
echo "Exercise 4: Changing file ownership"
echo "  sudo chown user:group file.txt     # Change owner and group"
echo "  sudo chown user file.txt           # Change owner only"
echo "  sudo chgrp group file.txt          # Change group only"
echo ""
echo "Exercise 5: Understanding sudo"
echo "  sudo command           # Run command as root"
echo "  sudo -i                # Become root user"
echo "  sudo -u user command   # Run command as specific user"
echo ""
echo "Exercise 6: Viewing other users"
echo "  cat /etc/passwd        # List all users"
echo "  cat /etc/group         # List all groups"
echo "  w                      # Who is logged in"
echo "  last                   # Login history"
echo ""

