#!/bin/bash
# Environment Variables and PATH Exercises

echo "=== Environment Variables and PATH Exercises ==="
echo ""
echo "Exercise 1: Viewing environment variables"
echo "  env                    # List all environment variables"
echo "  printenv               # Same as env"
echo "  echo \$HOME            # Print HOME variable"
echo "  echo \$USER            # Print USER variable"
echo "  echo \$SHELL           # Print SHELL variable"
echo ""
echo "Exercise 2: Understanding PATH"
echo "  echo \$PATH            # View current PATH"
echo "  which python3          # Find where python3 is located"
echo "  which ls               # Find where ls is located"
echo ""
echo "  The PATH variable tells the shell where to look for commands."
echo "  It's a colon-separated list of directories."
echo ""
echo "Exercise 3: Creating environment variables"
echo "  export MY_VAR='Hello'  # Create a variable"
echo "  echo \$MY_VAR          # Use the variable"
echo "  export NAME='DevUser'  # Create another variable"
echo "  echo \"My name is \$NAME\"  # Use in a string"
echo ""
echo "Exercise 4: Adding to PATH (temporary)"
echo "  export PATH=\$PATH:/home/user/bin  # Add directory to PATH"
echo "  echo \$PATH                        # Verify it was added"
echo ""
echo "Exercise 5: Making PATH changes permanent"
echo "  echo 'export PATH=\$PATH:/home/user/bin' >> ~/.bashrc"
echo "  source ~/.bashrc       # Reload the configuration"
echo ""
echo "  Or for all users:"
echo "  sudo nano /etc/environment"
echo ""
echo "Exercise 6: Common environment variables"
echo "  \$HOME      - Your home directory"
echo "  \$USER      - Your username"
echo "  \$SHELL     - Your default shell"
echo "  \$PATH      - Command search path"
echo "  \$PWD       - Current directory"
echo "  \$OLDPWD    - Previous directory"
echo "  \$LANG      - Language settings"
echo "  \$EDITOR    - Default text editor"
echo ""
echo "Exercise 7: Using variables in scripts"
echo "  Create a file 'test_env.sh' with:"
echo "    #!/bin/bash"
echo "    echo \"User: \$USER\""
echo "    echo \"Home: \$HOME\""
echo "    echo \"Custom: \$MY_VAR\""
echo ""
echo "Exercise 8: Unsetting variables"
echo "  unset MY_VAR           # Remove the variable"
echo "  echo \$MY_VAR          # Should be empty"
echo ""

