#!/bin/bash
# Advanced File Operations

echo "=== Advanced File Operations ==="
echo ""
echo "Exercise 1: Symbolic links (symlinks)"
echo "  ln -s /path/to/file link_name      # Create symlink"
echo "  ln -s /path/to/dir link_dir        # Link to directory"
echo "  ls -l link_name                    # View link"
echo "  readlink link_name                 # Show target"
echo "  readlink -f link_name              # Show absolute path"
echo ""
echo "Exercise 2: Hard links"
echo "  ln file.txt hardlink.txt           # Create hard link"
echo "  ls -li file.txt hardlink.txt       # Compare inodes"
echo ""
echo "  Difference:"
echo "    Symlink - pointer to filename (can cross filesystems)"
echo "    Hardlink - pointer to inode (same filesystem only)"
echo ""
echo "Exercise 3: File timestamps"
echo "  stat file.txt                      # All file info"
echo "  ls -l file.txt                     # Modification time"
echo "  ls -lu file.txt                    # Access time"
echo "  ls -lc file.txt                    # Change time"
echo ""
echo "Exercise 4: Changing timestamps with touch"
echo "  touch file.txt                     # Update to current time"
echo "  touch -t 202401150930 file.txt     # Set specific time"
echo "  touch -d '2024-01-15 09:30' file.txt  # Set with date string"
echo "  touch -r ref.txt file.txt          # Copy timestamp from ref.txt"
echo ""
echo "Exercise 5: Advanced find"
echo "  # Find by modification time"
echo "  find . -mtime -7                   # Modified in last 7 days"
echo "  find . -mtime +30                  # Modified more than 30 days ago"
echo "  find . -mmin -60                   # Modified in last 60 minutes"
echo ""
echo "  # Find by size"
echo "  find . -size +100M                 # Larger than 100MB"
echo "  find . -size -1k                   # Smaller than 1KB"
echo ""
echo "  # Find by permissions"
echo "  find . -perm 644                   # Exactly 644"
echo "  find . -perm -644                  # At least 644"
echo ""
echo "  # Find and execute"
echo "  find . -name '*.log' -exec rm {} \\;  # Delete all .log files"
echo "  find . -type f -exec chmod 644 {} \\; # Set permissions"
echo ""
echo "Exercise 6: Using xargs"
echo "  find . -name '*.txt' | xargs wc -l    # Count lines in all .txt files"
echo "  find . -name '*.log' | xargs rm       # Delete files (better than -exec)"
echo "  ls | xargs -I {} echo 'File: {}'      # Use placeholder"
echo "  cat files.txt | xargs -n 1 curl       # Process one at a time"
echo ""
echo "Exercise 7: File comparison"
echo "  diff file1.txt file2.txt           # Show differences"
echo "  diff -u file1.txt file2.txt        # Unified format"
echo "  diff -y file1.txt file2.txt        # Side-by-side"
echo "  diff -r dir1/ dir2/                # Compare directories"
echo "  cmp file1 file2                    # Binary comparison"
echo ""
echo "Exercise 8: Checksums"
echo "  md5sum file.txt                    # MD5 checksum"
echo "  sha256sum file.txt                 # SHA256 checksum"
echo "  sha256sum file.txt > file.txt.sha256  # Save checksum"
echo "  sha256sum -c file.txt.sha256       # Verify checksum"
echo ""
echo "  # Verify multiple files"
echo "  sha256sum *.txt > checksums.txt"
echo "  sha256sum -c checksums.txt"
echo ""
echo "Exercise 9: Finding duplicate files"
echo "  # By size first, then checksum"
echo "  find . -type f -exec md5sum {} \\; | sort | uniq -w32 -dD"
echo ""
echo "  # Using fdupes (if installed)"
echo "  fdupes -r directory/"
echo ""
echo "Exercise 10: File attributes (extended)"
echo "  lsattr file.txt                    # List attributes"
echo "  chattr +i file.txt                 # Make immutable (needs sudo)"
echo "  chattr -i file.txt                 # Remove immutable"
echo "  chattr +a file.txt                 # Append only"
echo ""
echo "Exercise 11: Real-world examples"
echo "  # Find and delete old log files"
echo "  find /var/log -name '*.log' -mtime +30 -exec rm {} \\;"
echo ""
echo "  # Find large files"
echo "  find / -type f -size +1G 2>/dev/null | xargs ls -lh"
echo ""
echo "  # Backup with verification"
echo "  cp important.txt backup.txt"
echo "  sha256sum important.txt backup.txt"
echo ""
echo "  # Find broken symlinks"
echo "  find . -type l ! -exec test -e {} \\; -print"
echo ""
echo "  # Find files modified today"
echo "  find . -type f -mtime 0"
echo ""
echo "  # Find empty files"
echo "  find . -type f -empty"
echo ""
echo "  # Find files owned by specific user"
echo "  find . -user username"
echo ""
echo "Exercise 12: Batch operations with xargs"
echo "  # Rename all .txt to .bak"
echo "  find . -name '*.txt' | xargs -I {} mv {} {}.bak"
echo ""
echo "  # Download multiple URLs"
echo "  cat urls.txt | xargs -n 1 -P 4 wget  # 4 parallel downloads"
echo ""
echo "  # Process files in parallel"
echo "  find . -name '*.jpg' | xargs -P 4 -I {} convert {} {}.png"
echo ""

