#!/bin/bash
# File Inspection Exercises

echo "=== File Inspection Exercises ==="
echo ""
echo "Exercise 1: Identify file types"
echo "  file sample_script.sh      # Bash script"
echo "  file sample_python.py      # Python script"
echo "  file sample_perl.pl        # Perl script"
echo "  file sample_text.txt       # Plain text"
echo "  file sample_binary         # Compiled executable"
echo "  file *                     # Check all files"
echo ""
echo "Exercise 2: View shebangs (first line of scripts)"
echo "  head -n 1 sample_script.sh"
echo "  head -n 1 sample_python.py"
echo "  head -n 1 sample_perl.pl"
echo "  head -n 1 sample_text.txt  # No shebang"
echo ""
echo "Exercise 3: Check if files are executable"
echo "  ls -l sample_*"
echo "  ls -l sample_script.sh | cut -d' ' -f1"
echo ""
echo "Exercise 4: Find the interpreter"
echo "  which bash"
echo "  which python3"
echo "  which perl"
echo ""
echo "Exercise 5: Understand command types"
echo "  type ls        # Built-in or external"
echo "  type cd        # Shell built-in"
echo "  type python3   # External command"
echo "  which ls       # Location of external commands"
echo ""
echo "Exercise 6: Inspect binary files"
echo "  file sample_binary"
echo "  strings sample_binary | grep 'This is'"
echo "  ldd sample_binary      # Show shared libraries"
echo ""
echo "Exercise 7: View file contents safely"
echo "  cat sample_text.txt    # Safe for text"
echo "  less sample_script.sh  # Page through"
echo "  head -n 5 sample_python.py  # First 5 lines"
echo "  tail -n 3 sample_perl.pl    # Last 3 lines"
echo ""
echo "Exercise 8: Find all executable files"
echo "  find . -type f -executable"
echo "  find . -type f -perm -u+x"
echo ""
echo "Exercise 9: Identify script type from shebang"
echo "  for file in sample_*.sh sample_*.py sample_*.pl; do"
echo "    echo -n \"\$file: \""
echo "    head -n 1 \$file"
echo "  done"
echo ""

