#!/bin/bash
# File Management Exercises

echo "=== File Management Exercises ==="
echo ""
echo "Exercise 1: Understanding where you are"
echo "  pwd                    # Print working directory"
echo "  ls                     # List files"
echo "  ls -la                 # List all files with details"
echo ""
echo "Exercise 2: Creating directories"
echo "  mkdir practice         # Create a directory"
echo "  mkdir -p deep/nested/dirs  # Create nested directories"
echo ""
echo "Exercise 3: Creating files"
echo "  touch myfile.txt       # Create an empty file"
echo "  echo 'Hello' > file.txt    # Create file with content"
echo "  echo 'World' >> file.txt   # Append to file"
echo ""
echo "Exercise 4: Viewing file contents"
echo "  cat file.txt           # Display entire file"
echo "  head file.txt          # First 10 lines"
echo "  tail file.txt          # Last 10 lines"
echo "  less file.txt          # Page through file (q to quit)"
echo ""
echo "Exercise 5: Copying files"
echo "  cp file.txt file_backup.txt        # Copy file"
echo "  cp -r directory/ directory_backup/ # Copy directory recursively"
echo ""
echo "Exercise 6: Moving/Renaming files"
echo "  mv file.txt newname.txt            # Rename file"
echo "  mv file.txt /path/to/destination/  # Move file"
echo ""
echo "Exercise 7: Deleting files"
echo "  rm file.txt            # Remove file"
echo "  rm -r directory/       # Remove directory and contents"
echo "  rm -rf directory/      # Force remove (be careful!)"
echo ""
echo "Exercise 8: Finding files"
echo "  find . -name '*.txt'   # Find all .txt files"
echo "  find . -type f         # Find all files"
echo "  find . -type d         # Find all directories"
echo ""
echo "Exercise 9: Understanding the filesystem"
echo "  cd /                   # Root directory"
echo "  ls /                   # List root contents"
echo "  cd /home               # User home directories"
echo "  cd /usr/bin            # User binaries"
echo "  cd /etc                # Configuration files"
echo "  cd ~                   # Your home directory"
echo "  cd -                   # Previous directory"
echo ""

