#!/bin/bash
# GNU Screen Guide

echo "=== GNU Screen - Terminal Multiplexer ==="
echo ""
echo "Why use screen?"
echo "  - Keep sessions running after disconnect"
echo "  - Multiple windows in one terminal"
echo "  - Share sessions with others"
echo "  - Essential for remote servers"
echo ""
echo "Exercise 1: Starting screen"
echo "  screen                 # Start new session"
echo "  screen -S mywork       # Start named session"
echo "  screen -ls             # List sessions"
echo ""
echo "Exercise 2: Basic screen commands (Ctrl+A then key)"
echo "  Ctrl+A then C          # Create new window"
echo "  Ctrl+A then N          # Next window"
echo "  Ctrl+A then P          # Previous window"
echo "  Ctrl+A then 0-9        # Switch to window number"
echo "  Ctrl+A then \"          # List all windows"
echo "  Ctrl+A then A          # Rename current window"
echo "  Ctrl+A then K          # Kill current window"
echo ""
echo "Exercise 3: Detaching and reattaching"
echo "  Ctrl+A then D          # Detach from session"
echo "  screen -r              # Reattach to session"
echo "  screen -r mywork       # Reattach to named session"
echo "  screen -d -r mywork    # Detach elsewhere and reattach here"
echo ""
echo "Exercise 4: Splitting screen"
echo "  Ctrl+A then S          # Split horizontally"
echo "  Ctrl+A then |          # Split vertically"
echo "  Ctrl+A then Tab        # Switch between regions"
echo "  Ctrl+A then X          # Close current region"
echo "  Ctrl+A then Q          # Close all regions except current"
echo ""
echo "Exercise 5: Copy mode (scrollback)"
echo "  Ctrl+A then [          # Enter copy mode"
echo "  # Use arrow keys or Vi keys to navigate"
echo "  # Press Space to start selection"
echo "  # Press Space again to copy"
echo "  Ctrl+A then ]          # Paste"
echo ""
echo "Exercise 6: Useful screen commands"
echo "  Ctrl+A then ?          # Help screen"
echo "  Ctrl+A then :          # Command prompt"
echo "  Ctrl+A then Esc        # Enter copy/scrollback mode"
echo "  Ctrl+A then H          # Toggle logging to file"
echo ""
echo "Exercise 7: Real-world workflow"
echo "  # Start a named session for a project"
echo "  screen -S webdev"
echo ""
echo "  # Window 0: Run development server"
echo "  python3 -m http.server 8000"
echo "  Ctrl+A then C  # Create new window"
echo ""
echo "  # Window 1: Edit code"
echo "  vim app.py"
echo "  Ctrl+A then C  # Create new window"
echo ""
echo "  # Window 2: Run tests"
echo "  pytest"
echo "  Ctrl+A then C  # Create new window"
echo ""
echo "  # Window 3: Monitor logs"
echo "  tail -f app.log"
echo ""
echo "  # Detach and go home"
echo "  Ctrl+A then D"
echo ""
echo "  # Next day, reattach"
echo "  screen -r webdev"
echo ""
echo "Exercise 8: Managing multiple sessions"
echo "  screen -ls             # List all sessions"
echo "  screen -r 12345        # Reattach by PID"
echo "  screen -X -S mywork quit  # Kill a session"
echo ""
echo "Exercise 9: Screen on remote servers"
echo "  # SSH to server"
echo "  ssh user@server"
echo ""
echo "  # Start screen session"
echo "  screen -S deployment"
echo ""
echo "  # Run long deployment"
echo "  ./deploy.sh"
echo ""
echo "  # Detach (Ctrl+A D) and logout"
echo "  # Connection lost? No problem!"
echo ""
echo "  # SSH back and reattach"
echo "  ssh user@server"
echo "  screen -r deployment"
echo ""
echo "Exercise 10: .screenrc configuration"
echo "  # Create ~/.screenrc with:"
echo "  # Set scrollback buffer"
echo "  defscrollback 10000"
echo ""
echo "  # Status line at bottom"
echo "  hardstatus alwayslastline"
echo "  hardstatus string '%{= kG}[ %{G}%H %{g}][%= %{= kw}%?%-Lw%?%{r}(%{W}%n*%f%t%?(%u)%?%{r})%{w}%?%+Lw%?%?%= %{g}][%{B} %m-%d %{W}%c %{g}]'"
echo ""
echo "  # Start windows automatically"
echo "  screen -t editor 0"
echo "  screen -t server 1"
echo "  screen -t logs 2"
echo ""
echo "Exercise 11: Common use cases"
echo "  # Long-running compilation"
echo "  screen -S build"
echo "  make -j8"
echo "  Ctrl+A then D"
echo ""
echo "  # IRC/chat client"
echo "  screen -S irc"
echo "  irssi"
echo "  Ctrl+A then D"
echo ""
echo "  # Download large file"
echo "  screen -S download"
echo "  wget http://example.com/largefile.iso"
echo "  Ctrl+A then D"
echo ""
echo "Exercise 12: Troubleshooting"
echo "  # Session is attached elsewhere"
echo "  screen -d -r sessionname   # Force detach and reattach"
echo ""
echo "  # Dead session"
echo "  screen -wipe               # Clean up dead sessions"
echo ""
echo "  # Can't find screen"
echo "  which screen               # Check if installed"
echo "  sudo apt install screen    # Install on Ubuntu/Debian"
echo ""

