#!/bin/bash
# System Information Commands

echo "=== System Information ==="
echo ""
echo "Exercise 1: System details with uname"
echo "  uname                  # Kernel name"
echo "  uname -a               # All information"
echo "  uname -r               # Kernel release"
echo "  uname -m               # Machine hardware"
echo "  uname -o               # Operating system"
echo ""
echo "Exercise 2: Disk space with df"
echo "  df                     # Disk space (blocks)"
echo "  df -h                  # Human-readable (GB, MB)"
echo "  df -h /                # Root filesystem only"
echo "  df -h --total          # Show total"
echo "  df -i                  # Inode information"
echo ""
echo "Exercise 3: Directory usage with du"
echo "  du -sh directory/      # Total size of directory"
echo "  du -h directory/       # Size of subdirectories"
echo "  du -ah directory/      # All files and directories"
echo "  du -h --max-depth=1    # One level deep"
echo "  du -sh * | sort -rh    # Largest directories first"
echo ""
echo "Exercise 4: Memory usage with free"
echo "  free                   # Memory in KB"
echo "  free -h                # Human-readable"
echo "  free -m                # In megabytes"
echo "  free -g                # In gigabytes"
echo "  free -h -s 2           # Update every 2 seconds"
echo ""
echo "Exercise 5: System uptime"
echo "  uptime                 # How long system has been running"
echo "  uptime -p              # Pretty format"
echo "  uptime -s              # Since when"
echo ""
echo "Exercise 6: Date and time"
echo "  date                   # Current date and time"
echo "  date +%Y-%m-%d         # Format: 2024-01-15"
echo "  date +%H:%M:%S         # Time only"
echo "  date +%s               # Unix timestamp"
echo "  date -d '2 days ago'   # Relative dates"
echo "  date -d @1234567890    # From timestamp"
echo ""
echo "Exercise 7: Calendar"
echo "  cal                    # Current month"
echo "  cal 2024               # Entire year"
echo "  cal 12 2024            # Specific month"
echo "  cal -3                 # Three months"
echo ""
echo "Exercise 8: Hostname and network info"
echo "  hostname               # System hostname"
echo "  hostname -I            # IP addresses"
echo "  hostname -f            # Fully qualified domain name"
echo ""
echo "Exercise 9: CPU information"
echo "  lscpu                  # CPU architecture info"
echo "  cat /proc/cpuinfo      # Detailed CPU info"
echo "  nproc                  # Number of processors"
echo ""
echo "Exercise 10: Memory information"
echo "  cat /proc/meminfo      # Detailed memory info"
echo "  vmstat                 # Virtual memory statistics"
echo "  vmstat 2 5             # Update every 2 seconds, 5 times"
echo ""
echo "Exercise 11: System load"
echo "  cat /proc/loadavg      # Load averages"
echo "  w                      # Who is logged in and load"
echo "  top -bn1 | head -5     # Top snapshot"
echo ""
echo "Exercise 12: Logged in users"
echo "  who                    # Who is logged in"
echo "  w                      # Who and what they're doing"
echo "  last                   # Login history"
echo "  last -n 10             # Last 10 logins"
echo "  lastlog                # Last login for all users"
echo ""
echo "Exercise 13: System logs"
echo "  dmesg                  # Kernel messages"
echo "  dmesg | tail           # Recent kernel messages"
echo "  dmesg | grep -i error  # Kernel errors"
echo "  journalctl -n 50       # Last 50 journal entries"
echo "  journalctl -f          # Follow journal"
echo ""
echo "Exercise 14: Hardware information"
echo "  lsblk                  # Block devices (disks)"
echo "  lsusb                  # USB devices"
echo "  lspci                  # PCI devices"
echo "  lshw                   # All hardware (needs sudo)"
echo ""
echo "Exercise 15: Real-world monitoring"
echo "  # Quick system overview"
echo "  echo '=== System Info ==='"
echo "  uname -a"
echo "  echo '=== Uptime ==='"
echo "  uptime"
echo "  echo '=== Disk Space ==='"
echo "  df -h /"
echo "  echo '=== Memory ==='"
echo "  free -h"
echo ""
echo "  # Find largest directories"
echo "  du -sh /* 2>/dev/null | sort -rh | head -10"
echo ""
echo "  # Check disk usage alert"
echo "  df -h | awk '\$5 > 80 {print \$0}'"
echo ""
echo "  # Memory usage by process"
echo "  ps aux --sort=-%mem | head -10"
echo ""

